
package org.lapps.datasource.trecgenomics;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import org.lappsgrid.api.DataSource;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrecPrimitiveDataSourceService", targetNamespace = "http://trecgenomics.datasource.lapps.org/", wsdlLocation = "http://localhost:9090/TrecPrimitiveDataSourceWS?wsdl")
public class TrecPrimitiveDataSourceService
    extends Service
{

    private final static URL TRECPRIMITIVEDATASOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRECPRIMITIVEDATASOURCESERVICE_EXCEPTION;
    private final static QName TRECPRIMITIVEDATASOURCESERVICE_QNAME = new QName("http://trecgenomics.datasource.lapps.org/", "TrecPrimitiveDataSourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/TrecPrimitiveDataSourceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRECPRIMITIVEDATASOURCESERVICE_WSDL_LOCATION = url;
        TRECPRIMITIVEDATASOURCESERVICE_EXCEPTION = e;
    }

    public TrecPrimitiveDataSourceService() {
        super(__getWsdlLocation(), TRECPRIMITIVEDATASOURCESERVICE_QNAME);
    }

    public TrecPrimitiveDataSourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRECPRIMITIVEDATASOURCESERVICE_QNAME, features);
    }

    public TrecPrimitiveDataSourceService(URL wsdlLocation) {
        super(wsdlLocation, TRECPRIMITIVEDATASOURCESERVICE_QNAME);
    }

    public TrecPrimitiveDataSourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRECPRIMITIVEDATASOURCESERVICE_QNAME, features);
    }

    public TrecPrimitiveDataSourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrecPrimitiveDataSourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataSource
     */
    @WebEndpoint(name = "TrecPrimitiveDataSourcePort")
    public DataSource getTrecPrimitiveDataSourcePort() {
        return super.getPort(new QName("http://trecgenomics.datasource.lapps.org/", "TrecPrimitiveDataSourcePort"), DataSource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataSource
     */
    @WebEndpoint(name = "TrecPrimitiveDataSourcePort")
    public DataSource getTrecPrimitiveDataSourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://trecgenomics.datasource.lapps.org/", "TrecPrimitiveDataSourcePort"), DataSource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRECPRIMITIVEDATASOURCESERVICE_EXCEPTION!= null) {
            throw TRECPRIMITIVEDATASOURCESERVICE_EXCEPTION;
        }
        return TRECPRIMITIVEDATASOURCESERVICE_WSDL_LOCATION;
    }

}
